// src/pages/DisclaimerPage.jsx
import React, { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, ShieldCheck, Terminal, Compass, ArrowLeft } from 'lucide-react'

export default function DisclaimerPage() {
  // Scroll to top on mount
  useEffect(() => {
    window.scrollTo({ top: 0 })
    const scrollContainers = document.querySelectorAll('.overflow-y-auto')
    scrollContainers.forEach(container => {
      container.scrollTo({ top: 0 })
    })
  }, [])

  return (
    <div className="max-w-4xl mx-auto px-6 py-12 space-y-8 animate-fade-in-up">
      {/* Title / Header */}
      <div className="border-b border-slate-200 dark:border-slate-800 pb-6">
        <Link 
          to="/" 
          className="inline-flex items-center gap-1.5 text-xs font-mono uppercase tracking-wider text-slate-500 dark:text-slate-400 hover:text-blue-500 dark:hover:text-cyber-glow mb-4 transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" /> Return to Terminal
        </Link>
        <h1 className="font-display font-black text-3xl sm:text-4xl uppercase tracking-wider text-slate-800 dark:text-white">
          General Disclaimer
        </h1>
        <p className="font-mono text-xs text-slate-400 dark:text-slate-500 uppercase tracking-widest mt-1">
          Model Classification Limitations // Updated: June 28, 2026
        </p>
      </div>

      {/* Warning Alert Banner */}
      <div className="p-5 border border-red-200/50 dark:border-red-950/40 bg-red-500/5 rounded-lg flex items-start gap-4">
        <div className="p-2.5 rounded bg-red-500/10 border border-red-500/20 text-red-500 shrink-0">
          <AlertTriangle className="w-5 h-5 animate-pulse" />
        </div>
        <div className="space-y-1">
          <h3 className="font-display font-bold text-xs uppercase tracking-wider text-slate-800 dark:text-white">Probabilistic Machine Learning Notice</h3>
          <p className="text-slate-500 dark:text-slate-400 text-xs leading-relaxed">
            All threat verdicts, risk percentages, and classifications generated by ThreatVaultZ are based on probabilistic statistical models. We do not provide categorical legal or technical guarantees regarding target safety.
          </p>
        </div>
      </div>

      {/* Main Body */}
      <div className="glass-card p-6 sm:p-8 border border-slate-200 dark:border-slate-800 bg-white/40 dark:bg-slate-950/30 text-xs sm:text-sm text-slate-600 dark:text-slate-300 font-body leading-relaxed space-y-6">
        
        <section className="space-y-2">
          <h2 className="font-display font-bold uppercase tracking-wider text-slate-800 dark:text-white text-sm sm:text-base flex items-center gap-2">
            <span className="font-mono text-red-500">01 //</span> Artificial Intelligence & ML Accuracy Limits
          </h2>
          <p>
            ThreatVaultZ employs local Random Forest classifiers, SMTP header tokenizers, and NLP body models. These machine learning heuristics score URLs, emails, and sites based on similarities to historically verified phishing domains and email templates. 
          </p>
          <p>
            Because adversaries continuously rotate domains, modify SSL configurations, and use polymorphic phishing templates, our scanners can generate:
          </p>
          <ul className="list-disc list-inside pl-4 space-y-1.5 pt-1">
            <li>
              <strong>False Positives:</strong> Safe, legitimate corporate pages or links might be labeled as "Suspicious" or "Phishing" due to layout geometry, newly registered domain states, or brand name keywords.
            </li>
            <li>
              <strong>False Negatives:</strong> Active, malicious phishing gateways might evade detection by exploiting zero-day host setups or using cloaked redirect loops that hide their elements from initial checks.
            </li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="font-display font-bold uppercase tracking-wider text-slate-800 dark:text-white text-sm sm:text-base flex items-center gap-2">
            <span className="font-mono text-red-500">02 //</span> Required Human Analyst Verification
          </h2>
          <p>
            ThreatVaultZ is designed as an advisory auxiliary tool. It does not replace a comprehensive Security Operations Center (SOC) manual check. Security analysts and system administrators must use their own discretion, verify results with sandbox executions, query reputable threat lookup servers (e.g., VirusTotal, AbuseIPDB), and consult official security advisors before blocking or white-listing domains.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-display font-bold uppercase tracking-wider text-slate-800 dark:text-white text-sm sm:text-base flex items-center gap-2">
            <span className="font-mono text-red-500">03 //</span> Exclusion of Cybersecurity Warranty
          </h2>
          <p>
            ThreatVaultZ is supplied "As Is" and "As Available" without warranty of any kind, whether express or implied. We do not warrant that our scanners will identify all threats, that the platform is immune to software errors, or that running the application will prevent ransomware, malware infections, account credential harvesting, or business email compromise (BEC).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-display font-bold uppercase tracking-wider text-slate-800 dark:text-white text-sm sm:text-base flex items-center gap-2">
            <span className="font-mono text-red-500">04 //</span> Third-Party Links & Intel Bulletins
          </h2>
          <p>
            Our bulletins and intelligence maps include hyperlinks to external threat feeds, reports, and security journals. ThreatVaultZ does not investigate or endorse the privacy protocols, content, or accuracy of these external sites. Clicking external links is done at the analyst's own risk.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-display font-bold uppercase tracking-wider text-slate-800 dark:text-white text-sm sm:text-base flex items-center gap-2">
            <span className="font-mono text-red-500">05 //</span> Updates to Model Parameters
          </h2>
          <p>
            Model parameters are updated periodically. Threat scores for identical targets can change between checks as our training weights adapt.
          </p>
        </section>
      </div>
    </div>
  )
}
